name: Docker Image CI

on:
  push:
    branches: [ wip/v3 ]

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
  REGISTRY_APPSALOON: portus.appsaloon.be
  APPSALOON_REGISTRY_USERNAME: ${{ secrets.DOCKERREGISTRYUSERNAME }}
  APPSALOON_REGISTRY_PASSWORD: ${{ secrets.DOCKERREGISTRYPASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: wip/v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},${{ env.REGISTRY_APPSALOON }}/${{ env.IMAGE_NAME }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry ${{ env.REGISTRY_APPSALOON }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_APPSALOON }}
          username: ${{ env.APPSALOON_REGISTRY_USERNAME }}
          password: ${{ env.APPSALOON_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Call the portainer webhook
        run: curl -X POST https://portainer.appsaloon.be/api/webhooks/fb04b38d-6454-4820-9ddc-6cfd8ca7a978
