name: Docker Image CI

on:
  push:
    branches: [ wip/v3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: wip/v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portus.appsaloon.be/gentlestudent/app:latest
    - name: Push the image
      env:
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKERREGISTRYUSERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERREGISTRYPASSWORD }}
      run: |
        docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD portus.appsaloon.be
        docker push portus.appsaloon.be/gentlestudent/app:latest
    - name: Call the portainer webhook
      run: curl -X POST https://portainer.appsaloon.be/api/webhooks/fb04b38d-6454-4820-9ddc-6cfd8ca7a978
